[project]
name = "renpy"
version = "0.1.0"
description = "renpy"
readme = "README.md"
requires-python = ">=3.9, <4.0"
dependencies = [
    "openai>=1.99.6",
    "websockets>=15.0.1",
]

[tool.nonebot]
adapters = [
]
plugins = []
plugin_dirs = ["src/plugins"]
builtin_plugins = ["echo"]

